repository_type: pipeline

nf_core_version: 3.5.1

lint: {}

template:
  org: nf-core
  name: virtus
  description: Implementation of VIRTUS2 in Nextflow
  author: Andrea Misiti
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - gpu
  is_nfcore: true
